"""add unique to telegram_id and skin_id

Revision ID: 110609cafe95
Revises: cc0c4080d80c
Create Date: 2025-05-07 15:37:09.529656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '110609cafe95'
down_revision: Union[str, None] = 'cc0c4080d80c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['telegram_id'])
    op.create_unique_constraint(None, 'skins', ['skin_id'])
    
    op.add_column('skins', sa.Column('telegram_user_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('skins_unique_user_id_fkey', 'skins', type_='foreignkey')
    op.create_foreign_key(None, 'skins', 'users', ['telegram_user_id'], ['telegram_id'])
    op.drop_column('skins', 'unique_user_id')
    op.alter_column('users', 'currency',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='currency::integer')
    op.drop_column('users', 'unique_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('unique_id', sa.BIGINT(), server_default=sa.text("nextval('users_unique_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'currency',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.add_column('skins', sa.Column('unique_user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'skins', type_='foreignkey')
    op.create_foreign_key('skins_unique_user_id_fkey', 'skins', 'users', ['unique_user_id'], ['unique_id'])
    op.drop_constraint(None, 'skins', type_='unique')
    op.drop_column('skins', 'telegram_user_id')
    # ### end Alembic commands ###
