"""foreign key in Skins

Revision ID: 3fae42523b5f
Revises: 719df2218fdb
Create Date: 2025-05-05 21:06:21.372719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fae42523b5f'
down_revision: Union[str, None] = '719df2218fdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skins', sa.Column('unique_user_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'skins', 'users', ['unique_user_id'], ['unique_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skins', type_='foreignkey')
    op.drop_column('skins', 'unique_user_id')
    # ### end Alembic commands ###
