"""telegram_id -> bigint

Revision ID: 524883cbce01
Revises: d1385768b289
Create Date: 2025-04-29 15:49:43.178228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '524883cbce01'
down_revision: Union[str, None] = 'd1385768b289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram_id',
               existing_type=sa.VARCHAR(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               postgresql_using='telegram_id::bigint')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
