"""MTO for Users and Skins

Revision ID: 5faad3e1f564
Revises: 524883cbce01
Create Date: 2025-05-05 15:52:39.190603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5faad3e1f564'
down_revision: Union[str, None] = '524883cbce01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secondary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secondary',
    sa.Column('users_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('skins_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['skins_name'], ['skins.name'], name='secondary_skins_name_fkey'),
    sa.ForeignKeyConstraint(['users_id'], ['users.unique_id'], name='secondary_users_id_fkey'),
    sa.PrimaryKeyConstraint('users_id', 'skins_name', name='secondary_pkey')
    )
    # ### end Alembic commands ###
