"""telegram_id is primary_key

Revision ID: 85f1cf0904b7
Revises: 35305aa1b439
Create Date: 2025-05-07 14:17:21.982235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85f1cf0904b7'
down_revision: Union[str, None] = '35305aa1b439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skins', sa.Column('telegram_user_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('skins_unique_user_id_fkey', 'skins', type_='foreignkey')
    op.create_foreign_key(None, 'skins', 'users', ['telegram_user_id'], ['telegram_id'])
    op.drop_column('skins', 'unique_user_id')
    op.drop_column('users', 'unique_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('unique_id', sa.BIGINT(), server_default=sa.text("nextval('users_unique_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.add_column('skins', sa.Column('unique_user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'skins', type_='foreignkey')
    op.create_foreign_key('skins_unique_user_id_fkey', 'skins', 'users', ['unique_user_id'], ['unique_id'])
    op.drop_column('skins', 'telegram_user_id')
    # ### end Alembic commands ###
