"""percent, current_price in Skins

Revision ID: c115e74d2f1e
Revises: 5faad3e1f564
Create Date: 2025-05-05 15:57:35.955263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c115e74d2f1e'
down_revision: Union[str, None] = '5faad3e1f564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skins', sa.Column('current_price', sa.Float(), nullable=False))
    op.add_column('skins', sa.Column('percent', sa.Integer(), nullable=True))
    op.drop_column('skins', 'last_price')
    op.drop_column('skins', 'update_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skins', sa.Column('update_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('skins', sa.Column('last_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('skins', 'percent')
    op.drop_column('skins', 'current_price')
    # ### end Alembic commands ###
