"""currency to int

Revision ID: cc0c4080d80c
Revises: 85f1cf0904b7
Create Date: 2025-05-07 14:47:19.635522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc0c4080d80c'
down_revision: Union[str, None] = '85f1cf0904b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skins', sa.Column('telegram_user_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('skins_unique_user_id_fkey', 'skins', type_='foreignkey')
    op.create_foreign_key(None, 'skins', 'users', ['telegram_user_id'], ['telegram_id'])
    op.drop_column('skins', 'unique_user_id')
    op.alter_column('users', 'currency',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_column('users', 'unique_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('unique_id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.alter_column('users', 'currency',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.add_column('skins', sa.Column('unique_user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'skins', type_='foreignkey')
    op.create_foreign_key('skins_unique_user_id_fkey', 'skins', 'users', ['unique_user_id'], ['unique_id'])
    op.drop_column('skins', 'telegram_user_id')
    # ### end Alembic commands ###
