"""initial

Revision ID: d1385768b289
Revises: 
Create Date: 2025-04-28 07:42:40.962454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1385768b289'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skins',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('update_price', sa.Float(), nullable=True),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('users',
    sa.Column('unique_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_id', sa.String(), nullable=False),
    sa.Column('telegram_username', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('notify', sa.Boolean(), nullable=False),
    sa.Column('timer', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('unique_id')
    )
    op.create_table('secondary',
    sa.Column('users_id', sa.BigInteger(), nullable=False),
    sa.Column('skins_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['skins_name'], ['skins.name'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.unique_id'], ),
    sa.PrimaryKeyConstraint('users_id', 'skins_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secondary')
    op.drop_table('users')
    op.drop_table('skins')
    # ### end Alembic commands ###
